NaniQR2/NaniQR2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


admin.AdminSite.site_header = 'MYCELIUM'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('',include('purchase.urls')),
    path('',include('cart.urls')),
    path('',include('catagories.urls'))
    
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

NaniQR2/cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
path('', views.cart_detail, name='cart_detail'),
path('add/<int:product_id>/', views.cart_add, name='cart_add'),
path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),

]

NaniQR2/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)
    cus_name = forms.CharField(max_length=100)
    price = forms.IntegerField()
    message = forms.CharField(widget=forms.Textarea)
    location = forms.CharField()
    purchased = forms.BooleanField(required=False)

    

NaniQR2/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catagories.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'],
                 cus_name=cd['cus_name'],
                 price=cd['price'],
                 message=cd['message'],
                 location=cd['location'],
                 purchased=cd['purchased'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                              initial={'quantity': item['quantity'],
                              'update': True,
                              'cus_name': item['cus_name'],
                              'price': item['price'],
                              'message': item['message'],
                              'location': item['location'],
                              'message': False,})
    return render(request, 'cart/detail.html', {'cart': cart})

NaniQR2/cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="center">
	{% csrf_token %}
  <h1>የእርሶ ትዕዛዞች ዝርዝር መረጃ</h1>
  {% for item in cart %}
    {% with product=item.product %}
      <h4 class="text-center">{{ product.name }}</h4>
      <hr>
      <form action="{% url "cart:cart_add" product.id %}" method="post">
        {{ item.update_quantity_form.quantity }}
        {{ item.update_quantity_form.update }}
        <input type="submit" value="አስተካክል">
        {% csrf_token %}
      </form>
      <hr>
      <div>
        <a href="{% url "cart:cart_remove" product.id %}">ሰርዝ</a>
      </div>
      <hr>
      <div>
        <a class="text-center">{{ item.price }} ብር</a>
      </div>
    {% endwith %}
  {% endfor %}
  <p class="text-center">
    <a href="{% url "shop:product_list" %}" class="btn btn-primary cta">ግብይቶን ይቀጥሉ</a>
    <a href="{% url "orders:order_create" %}" class="btn btn-primary cta">
      ትዕዛዞትን ይላኩ
    </a>
  </p>
{% endblock %}
    